# Final Project 
# University of California - Berkeley 

# Creators: Charis Liao, Jeffy Jeffy, Joshua Blomgren  
# Data: 12/12/2022 

# This makefile creates the object file containing the random number generator function.
# These files are then moved to the ../../Libdir subdirectory

# The makefile is called by the main makefile in the main directory.

RANDGEN = ./Randgen

# The target will compile the source code for the random number generator function
# The object files will be located in the Libdir subdirectory
all: 
	cd $(RANDGEN); make all

# The target will remove all the object files created by the makefile
cleanall:
	cd $(RANDGEN); make cleanall

