# Final Project 
# University of California - Berkeley 

# Creators: Charis Liao, Jeffy Jeffy, Joshua Blomgren  
# Data: 12/12/2022 

# This makefile creates the object files that are the source code of the cellular automata model. 
# These files are then moved to the ../../Libdir subdirectory

# The makefile is called by the main makefile in the main directory.

CA_MODEL = ./CA_model


# The target will compile the source code for the cellular automata model class
# The object files will be located in the Libdir subdirectory 
all: 
	cd $(CA_MODEL); make all
	

# The target will remove all the object files created by the makefile
cleanall:
	cd $(CA_MODEL); make cleanall
	